# URL de la base de datos con tu nombre personalizado
spring.datasource.url=jdbc:h2:file:./data/barbershopdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver

# Credenciales personalizadas
spring.datasource.username=claudiaypablo
spring.datasource.password=1234

# ==============================================================
# H2 CONSOLE CONFIGURATION
# ==============================================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Esto asegura que use siempre el nombre 'TheKielceBarber' y no uno aleatorio
spring.datasource.generate-unique-name=false
spring.datasource.name=TheKielceBarber

# ==============================================================
# JPA / HIBERNATE SETTINGS
# ==============================================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.oauth2.client.registration.google.client-id=257970284375-j85e3vbnkei564cdkv7ogagi55kmf72l.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Reduce el ruido de logs de RabbitMQ
logging.level.org.springframework.amqp=WARN
logging.level.org.springframework.retry=ERROR

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB