spring.datasource.url=jdbc:h2:mem:barberdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

spring.security.oauth2.client.registration.google.client-id=257970284375-j85e3vbnkei564cdkv7ogagi55kmf72l.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Reduce el ruido de logs de RabbitMQ
logging.level.org.springframework.amqp=WARN
logging.level.org.springframework.retry=ERROR